Global:
  device: gpu
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/resnet_syn/
  save_epoch_step: [150, 10]
  # evaluation is run every 2000 iterations
  eval_epoch_step: [0, 10]
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints:
  use_tensorboard: false
  infer_img: /scratch/penghao/datasets/Date-Real/eval/images
  # for data or label process
  character_dict_path: &character_dict_path ./tools/utils/EN_symbol_dict.txt
  max_text_length: &max_text_length 25
  use_space_char: &use_space_char True
  save_res_path: ./output/rec/u14m_filter/predicts_svtrv2_ctc.txt
  use_amp: True
  project_name: resvtr_ctc_nosgm_ds

Optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 3.0e-05
  filter_bias_and_bn: False

LRScheduler:
  name: CosineAnnealingLR
  warmup_epoch: 5

Architecture:
  model_type: rec
  algorithm: SVTRv2_mobile
  Transform:
  Encoder:
    name: TIMMTrans
    model_name: resnet50.a1_in1k
    pretrained: True
    out_indices: [1, 2]
    out_dim: 256
    trans_layer: 3
    last_stage: False
  Decoder:
    name: CTCDecoder
    svtr_encoder:
      dims: 256
      depth: 2
      hidden_dims: 256
      kernel_size: [1, 3]
      use_guide: True

Loss:
  name: CTCLoss
  zero_infinity: True

PostProcess:
  name: CTCLabelDecode
  character_dict_path: *character_dict_path

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False
  # is_filter: True

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /scratch/penghao/datasets/Date-Syn/out
    label_file_list:
      - /scratch/penghao/datasets/Date-Syn/train_labels_fixed.txt
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - PARSeqAugPIL:
      - CTCLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - RecTVResize:
          image_shape: [48, 320]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: True
    batch_size_per_card: 1120
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /scratch/penghao/datasets/Date-Real/eval/images
    label_file_list:
      - /scratch/penghao/datasets/Date-Real/eval/labels_fixed.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
      - CTCLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - RecDynamicResize:
          image_shape: [48, 320]
          padding: False
      # - SVTRResize:
      #     image_shape: [3, 48, 320]
      #     padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 8
